theme: jekyll-theme-minimal
title: René Gabriel Navarro Labastida
logo: https://raw.githubusercontent.com/enerle/enerle.github.io/main/pic2.jpg
description: Oceanografía de sofá y elaboración de pizzas. Entusiasta de los libros y del Acqua Frizzante.
