theme: jekyll-theme-minimal
title: René Gabriel Navarro-Labastida
logo: https://raw.githubusercontent.com/enerle/rnavarro.github.io/main/pic2.jpg
description: Ocean Modeling and Climate Variability, Physical Oceanography, Ocean Dynamics
