theme: jekyll-theme-minimal
title: René Gabriel Navarro Labastida
logo: https://raw.githubusercontent.com/enerle/enerle.github.io/main/pic2.jpg
description: Especialista en Oceanografía de sofá y entusiasta del Acqua Frizzante.
