theme: jekyll-theme-minimal
title: René Gabriel Navarro-Labastida
logo: https://raw.githubusercontent.com/enerle/enerle.github.io/main/pic2.jpg
description: Physical Oceanography, Climate Variability, Ocean Dynamics and Ocean Modeling
